config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category, optional: true
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    if params[:search].present?
      @categories = Category.where("name ILIKE ?", params[:search]).or(Category.where("details ILIKE ?", "%#{params[:search]}%"))
    else
      @categories = Category.all
    end
  end

  def show
    find_category
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_url(@category)
    else
      render :new
    end
  end

  def edit
    find_category
  end

  def update
    find_category

    if @category.update 
      redirect_to @category
    else 
      render :edit, status: :unprocessable_entity
    end 
  end

  def destroy
    find_category
    @category.destroy 
    redirect_to root_path, status: :see_other
  end

  private

    def find_category
      @category = Category.find(params[:id])
    end

    def category_params

      params.require(:category).permit(:name, :category_id, :details)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <h3>Edit <%@category.name %> </h3>
    <form>
      <div class="mt-3 container-fluid">
        <%= form_with model: @category do |form| %>
        <div class="row mb-3">
            <%= form.label :name, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :name, placeholder: "Category Name", class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
            <%= form.label :details, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :details, placeholder: "Details", class: "form-control" %>
          </div>
        </div>
        <div class="row mb-3">
            <%= form.label :category_id, class:"col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.select :category_id, Category.where(category_id: nil).map { |c| [c.name, c.id] }, class: "form-control form-select" %>
          </div>
        </div>
        <br>
        <div>
          <%= form.submit "Create", class:"btn btn-primary" %>
        </div>
      <% end %>
    </form>
  <div class="col-3"></div>
</div>

app/views/categories/index.html.erb
<div class="row mt-3">
  <div class="col">
    <h3>All Categories</h3>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%= link_to "Add Category", new_category_url(@category), class:"btn btn-primary" %>
  </div>
  <div class="col"></div>
  <div class="col">
    <%= form_tag(categories_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
</div>


<div class="row mt-3">
  <div class="col">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Parent Category</th>
          <th scope="col">Details</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td><%= category.category&.name %></td>
          <td><%= category.details %></td>
          <td>
            <%=link_to "View", category, class:" btn btn-info" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row mt-4">
  <div class="col-3"></div>
  <div class="col-6">
    <h3>Create new category</h3>
      <div class="mt-3 container-fluid">
        <%= form_with model: @category do |form| %>
          <div class="row mb-3">
              <%= form.label :name, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :name, placeholder: "Category Name", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :details, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.text_field :details, placeholder: "Details", class: "form-control" %>
            </div>
          </div>
          <div class="row mb-3">
              <%= form.label :category_id, class:"col-sm-2 col-form-label" %>
            <div class="col-sm-10">
            <%= form.select :category_id, Category.where(category_id: nil).map { |c| [c.name, c.id] }, class: "form-control form-select" %>
            </div>
          </div>
          <br>
          <div>
            <%= form.submit "Create", class:"btn btn-primary" %>
          </div>
      <% end %>
  <div class="col-3"></div>
</div>

app/views/categories/show.html.erb
<div class="row mt-3">
  <div class="col">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @category.name %> Details</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">
          <%=
            if @category.category 
              "Sub Category"
             else 
              "Main Category"
            end 
          %>
        </h6>
        <p class="card-text"><%= @category.details %></p>
        <div>
        <%= link_to "Add new", new_category_url, class:"btn btn-primary" %>
        <%= link_to "edit", edit_category_url(@category), class:"btn btn-warning" %>
        <%= button_to "Delete", category_path(@category), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Dordam" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://127.0.0.1:3000/">Dordam</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Categories", categories_url, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex">
        <button class="btn btn-outline-success">Log In</button>
      </div>
    </div>
  </div>
</nav>